### PR TITLE
Epmlabssum 42

### PR DESCRIPTION
**Pull request by jaureguif**
Add business provider endpoint

### CODE REVIEW

**Review by dan-zx — APPROVED** [review]
Looks good. 
Please, try to follow the code standards using the templates I put in the folder *code-style* to comply the code style as much as possible

**Review by snakeup — APPROVED** [review]
Looks good

**Review by ulises-mancilla — APPROVED** [review]
LGTM

**Review by dioniciorodriguez — COMMENTED** [review]
k

**Pull request merged**
